# .github/workflows/build-and-deploy.yml

name: CITROS WEB CI

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  # update the Node version to meet your needs
                  node-version: 16
                  cache: npm

            - name: Build
              run: |
                  npm ci
                  npm run build
                  npm run export
                  touch _static/.nojekyll

            - name: Deploy
              # configure an external GitHub Pages deploy workflow here
              uses: JamesIves/github-pages-deploy-action
              with:
                  branch: gh-pages
                  folder: _static
